# Generated by Django 3.2.13 on 2023-11-12 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0003_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapternumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
