# Generated by Django 3.2.13 on 2023-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
