# Generated by Django 3.2.13 on 2023-11-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0006_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
