# Generated by Django 3.2.13 on 2023-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0007_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
