# Generated by Django 3.2.13 on 2023-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0008_auto_20231115_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
