# Generated by Django 3.2.13 on 2023-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0010_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
