# Generated by Django 3.2.13 on 2023-11-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrackerapp', '0012_auto_20231122_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
